### ISSUE TITLE
https proxies aren't https

### ISSUE THREAD

**Issue by Sneffel** [proxifly/free-proxy-list#8]
Hi. Maybe I'm not missing something, but every https proxy is actually http. So, https connections fail. 

For example, 
http://httpbin.org/ip is fine
https://httpbin.org/ip fails

What's the point of having an https list if it's got no https working proxy?

**Comment by hw630590** [comment]
It works for me, maybe it's just your code.

**Comment by Sneffel** [comment]
_...but it works on my machine!_
Well, thanks, I guess. 
I made it work with 🧦5.
